// Package oauth contains platform-specific authentication clients.
//
// For Bluesky, "OAuth" means creating a session with a user-provided
// app password (not the classic OAuth redirect flow).
package oauth

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"strings"
	"time"
)

// BlueskyBaseURL is the public Bluesky PDS for hosted accounts.
// Self-hosted users have their own PDS URLs; we only support the
// default hosted instance for now.
const BlueskyBaseURL = "https://bsky.social"

// BlueskyClient talks to the Bluesky AT Protocol.
type BlueskyClient struct {
	httpClient *http.Client
	baseURL    string
}

// NewBlueskyClient creates a new Bluesky API client.
func NewBlueskyClient() *BlueskyClient {
	return &BlueskyClient{
		httpClient: &http.Client{Timeout: 30 * time.Second},
		baseURL:    BlueskyBaseURL,
	}
}

// Session holds the tokens returned by Bluesky after createSession.
type Session struct {
	AccessJwt  string
	RefreshJwt string
	DID        string
	Handle     string
	Email      string
}

// createSessionRequest is the JSON body for com.atproto.server.createSession.
type createSessionRequest struct {
	Identifier string `json:"identifier"` // handle or email
	Password   string `json:"password"`   // app password
}

// sessionResponse is the JSON shape returned by createSession and refreshSession.
type sessionResponse struct {
	AccessJwt  string `json:"accessJwt"`
	RefreshJwt string `json:"refreshJwt"`
	DID        string `json:"did"`
	Handle     string `json:"handle"`
	Email      string `json:"email,omitempty"`
}

// CreateSession authenticates with a handle + app password.
//
// The app password must be generated by the user at:
//
//	https://bsky.app/settings/app-passwords
func (c *BlueskyClient) CreateSession(
	ctx context.Context,
	handle string,
	appPassword string,
) (*Session, error) {
	handle = strings.TrimSpace(handle)
	appPassword = strings.TrimSpace(appPassword)

	if handle == "" {
		return nil, fmt.Errorf("handle is required")
	}
	if appPassword == "" {
		return nil, fmt.Errorf("app password is required")
	}

	body, err := json.Marshal(createSessionRequest{
		Identifier: handle,
		Password:   appPassword,
	})
	if err != nil {
		return nil, fmt.Errorf("failed to encode request: %w", err)
	}

	url := c.baseURL + "/xrpc/com.atproto.server.createSession"
	req, err := http.NewRequestWithContext(ctx, http.MethodPost, url, bytes.NewReader(body))
	if err != nil {
		return nil, fmt.Errorf("failed to create request: %w", err)
	}

	req.Header.Set("Content-Type", "application/json")

	resp, err := c.httpClient.Do(req)
	if err != nil {
		return nil, fmt.Errorf("bluesky request failed: %w", err)
	}
	defer resp.Body.Close()

	respBody, _ := io.ReadAll(resp.Body)

	if resp.StatusCode == http.StatusUnauthorized {
		return nil, fmt.Errorf("invalid handle or app password")
	}
	if resp.StatusCode < 200 || resp.StatusCode >= 300 {
		// Do not include full body in error (may contain hints about auth)
		return nil, fmt.Errorf("bluesky returned HTTP %d", resp.StatusCode)
	}

	var session sessionResponse
	if err := json.Unmarshal(respBody, &session); err != nil {
		return nil, fmt.Errorf("failed to decode response: %w", err)
	}

	if session.AccessJwt == "" || session.RefreshJwt == "" || session.DID == "" {
		return nil, fmt.Errorf("bluesky returned incomplete session")
	}

	return &Session{
		AccessJwt:  session.AccessJwt,
		RefreshJwt: session.RefreshJwt,
		DID:        session.DID,
		Handle:     session.Handle,
		Email:      session.Email,
	}, nil
}

// RefreshSession exchanges a refresh JWT for a new access JWT.
//
// Used when the access JWT is close to expiry. In Stage 1 we don't
// call this yet; it's here for the future publish endpoint.
func (c *BlueskyClient) RefreshSession(
	ctx context.Context,
	refreshJwt string,
) (*Session, error) {
	if refreshJwt == "" {
		return nil, fmt.Errorf("refresh JWT is required")
	}

	url := c.baseURL + "/xrpc/com.atproto.server.refreshSession"
	req, err := http.NewRequestWithContext(ctx, http.MethodPost, url, nil)
	if err != nil {
		return nil, fmt.Errorf("failed to create request: %w", err)
	}

	req.Header.Set("Authorization", "Bearer "+refreshJwt)

	resp, err := c.httpClient.Do(req)
	if err != nil {
		return nil, fmt.Errorf("bluesky refresh failed: %w", err)
	}
	defer resp.Body.Close()

	respBody, _ := io.ReadAll(resp.Body)

	if resp.StatusCode == http.StatusUnauthorized {
		return nil, fmt.Errorf("refresh JWT is invalid or expired")
	}
	if resp.StatusCode < 200 || resp.StatusCode >= 300 {
		return nil, fmt.Errorf("bluesky returned HTTP %d", resp.StatusCode)
	}

	var session sessionResponse
	if err := json.Unmarshal(respBody, &session); err != nil {
		return nil, fmt.Errorf("failed to decode refresh response: %w", err)
	}

	if session.AccessJwt == "" || session.RefreshJwt == "" {
		return nil, fmt.Errorf("bluesky returned incomplete refresh session")
	}

	return &Session{
		AccessJwt:  session.AccessJwt,
		RefreshJwt: session.RefreshJwt,
		DID:        session.DID,
		Handle:     session.Handle,
		Email:      session.Email,
	}, nil
}

// DeleteSession revokes the current access JWT (logs out).
//
// Called on disconnect. Failure here is not fatal — we still remove
// the local connection record.
func (c *BlueskyClient) DeleteSession(
	ctx context.Context,
	accessJwt string,
) error {
	if accessJwt == "" {
		return nil
	}

	url := c.baseURL + "/xrpc/com.atproto.server.deleteSession"
	req, err := http.NewRequestWithContext(ctx, http.MethodPost, url, nil)
	if err != nil {
		return fmt.Errorf("failed to create request: %w", err)
	}

	req.Header.Set("Authorization", "Bearer "+accessJwt)

	resp, err := c.httpClient.Do(req)
	if err != nil {
		return fmt.Errorf("bluesky delete failed: %w", err)
	}
	defer resp.Body.Close()

	// Accept any 2xx as success. 401 here means the token was already
	// invalid — which is also fine for us.
	if resp.StatusCode >= 200 && resp.StatusCode < 300 {
		return nil
	}
	if resp.StatusCode == http.StatusUnauthorized {
		return nil
	}

	return fmt.Errorf("bluesky returned HTTP %d", resp.StatusCode)
}

// Profile holds a Bluesky user's public profile info.
type Profile struct {
	DID         string
	Handle      string
	DisplayName string
	Avatar      string
}

// GetProfile fetches a user's profile by handle.
//
// Uses the app.bsky.actor.getProfile XRPC endpoint.
// Failure here is non-fatal for connect flows — caller should just
// proceed without a display name.
func (c *BlueskyClient) GetProfile(
	ctx context.Context,
	accessJwt string,
	handle string,
) (*Profile, error) {
	if accessJwt == "" {
		return nil, fmt.Errorf("access JWT is required")
	}
	if handle == "" {
		return nil, fmt.Errorf("handle is required")
	}

	url := c.baseURL + "/xrpc/app.bsky.actor.getProfile?actor=" + handle
	req, err := http.NewRequestWithContext(ctx, http.MethodGet, url, nil)
	if err != nil {
		return nil, fmt.Errorf("failed to create profile request: %w", err)
	}

	req.Header.Set("Authorization", "Bearer "+accessJwt)

	resp, err := c.httpClient.Do(req)
	if err != nil {
		return nil, fmt.Errorf("profile request failed: %w", err)
	}
	defer resp.Body.Close()

	if resp.StatusCode < 200 || resp.StatusCode >= 300 {
		return nil, fmt.Errorf("bluesky profile returned HTTP %d", resp.StatusCode)
	}

	var raw struct {
		DID         string `json:"did"`
		Handle      string `json:"handle"`
		DisplayName string `json:"displayName"`
		Avatar      string `json:"avatar"`
	}

	if err := json.NewDecoder(resp.Body).Decode(&raw); err != nil {
		return nil, fmt.Errorf("failed to decode profile: %w", err)
	}

	return &Profile{
		DID:         raw.DID,
		Handle:      raw.Handle,
		DisplayName: raw.DisplayName,
		Avatar:      raw.Avatar,
	}, nil
}
